INSERT INTO public."Types"(id, name, "damageClass")
VALUES (1,'bug','physical'),
(2,'dark','special'),
(3,'dragon','special'),
(4,'electric','special'),
(5,'fairy',''),
(6,'fighting','physical'),
(7,'fire','special'),
(8,'flying','physical'),
(9,'ghost','physical'),
(10,'grass','special'),
(11,'ground','physical'),
(12,'ice','special'),
(13,'normal','physical'),
(14,'poison','physical'),
(15,'psychic','special'),
(16,'rock','physical'),
(17,'steel','physical'),
(18,'water','special');