name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pokemon_api
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
    - uses: actions/checkout@v3
      with:
        path: "app"
    - run: "npm install"
      working-directory: "app"
    - run: "npx sequelize-cli db:migrate --env test"
      working-directory: "app"
    - run: "npx sequelize-cli db:seed:all --env test"
      working-directory: "app"
    - run: "npm run build"
      working-directory: "app"
    - run: "node -r dotenv/config . &> serverlog.txt &"
      working-directory: "app"
    - uses: actions/checkout@v3
      with:
        repository: "monktana/jest-pokemon-api"
        path: "tests"
    - run: "npm install && npm run test"
      working-directory: "tests"
    - run: "cat serverlog.txt"
      working-directory: "app"
      if: always()
